name: tempestade
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#a9aaa4'
    - '#726e62'
    - '#908f8a'
    - '#424242'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
