name: tempestade
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8357595053967088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#786b6a'
    - '#948c8d'
    - '#000000'
    - '#473a39'
    - '#b4b38c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
